# Generated by Django 4.1.3 on 2022-12-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='pho',
            field=models.CharField(max_length=10),
        ),
    ]
